py-run:
	cd python && uv run word_count --input ../../../shared/fixtures/word-count.txt

py-test:
	cd python && uv run pytest

ts-run:
	cd typescript && bun run src/main.ts --input ../../../shared/fixtures/word-count.txt

ts-test:
	cd typescript && bun test
